/* JSP·OS pixel icon generator — 16x16 hand-mapped sprites → crisp SVG */
import fs from 'fs';

const PAL = {
  K: '#211d19', // ink outline
  W: '#f6f1e3', // cream
  w: '#ffffff',
  O: '#ff6b35', // orange
  Y: '#ffb347', // amber
  B: '#4a8fd9', // blue
  L: '#8fc3f0', // light blue
  G: '#4caf7d', // green
  M: '#a7c957', // light green
  P: '#9b7ede', // purple
  N: '#e88bb5', // pink
  R: '#e05252', // red
  D: '#5d564c', // dark neutral
};

const ICONS = {
today: [
'................',
'.......KK.......',
'..K...KYYK...K..',
'..KK..KYYK..KK..',
'...KKKYYYYKKK...',
'...KYYYYYYYYK...',
'.KKKYYOOOOYYKKK.',
'.KYYYOOOOOOYYYK.',
'.KYYYOOOOOOYYYK.',
'.KKKYYOOOOYYKKK.',
'...KYYYYYYYYK...',
'...KKKYYYYKKK...',
'..KK..KYYK..KK..',
'..K...KYYK...K..',
'.......KK.......',
'................',
],
planner: [
'................',
'..KKKKKKKKKKK...',
'..KWWWWWWWWWK...',
'..KWKKWWWWWWK...',
'..KWKKWKKKKWK...',
'..KWWWWWWWWWK...',
'..KWKKWWWWWWK...',
'..KWKKWKKKKWK...',
'..KWWWWWWWWWK...',
'..KWGGWWWWWWK...',
'..KWGGWKKKWWK...',
'..KWWWWWWWWWK...',
'..KWWWWWWWWWK...',
'..KKKKKKKKKKK...',
'................',
'................',
],
meds: [
'................',
'..........K.....',
'................',
'....KKKKKKKK....',
'...KWWWWNNNNK...',
'..KWwWWWNNNNNK..',
'..KWwWWWNNNNNK..',
'..KWWWWWNNNNNK..',
'..KWWWWWNNNNNK..',
'...KWWWWNNNNK...',
'....KKKKKKKK....',
'.....K..........',
'.............K..',
'..K.............',
'................',
'................',
],
routines: [
'................',
'.....KKKKKK.....',
'....KGGGGGGK....',
'...KGGKKKKGGK...',
'...KGK....KGK...',
'...KGK....KGKK..',
'...KGK...KGGGK..',
'...KGK....KGK...',
'...KGK.....K....',
'...KGK..........',
'....KGK....K....',
'..KKGGK...KGK...',
'..KGGGKKKKGGK...',
'...KGGGGGGGK....',
'....KKKKKKK.....',
'................',
],
journal: [
'................',
'..........KKK...',
'.........KNNNK..',
'........KNNNNK..',
'.......KYYKNNK..',
'......KYYYYKK...',
'.....KYYYYYK....',
'....KYYYYYK.....',
'...KYYYYYK......',
'...KWYYYK.......',
'..KWWYYK........',
'..KWWWK.........',
'..KKWK..........',
'..KKK...........',
'................',
'................',
],
trackers: [
'................',
'................',
'..........KKK...',
'..........KPK...',
'..........KPK...',
'......KKK.KPK...',
'......KBK.KPK...',
'......KBK.KPK...',
'..KKK.KBK.KPK...',
'..KOK.KBK.KPK...',
'..KOK.KBK.KPK...',
'..KOK.KBK.KPK...',
'.KKKKKKKKKKKKK..',
'................',
'................',
'................',
],
collections: [
'................',
'....KKKK.KKKK...',
'....KWWK.KNNK...',
'...KWWWK.KNNNK..',
'...KWWK..KNNK...',
'..KKKKKKKKKKKK..',
'..KYYYYYYYYYYK..',
'..KYKKKKKKKKYK..',
'..KYYYYYYYYYYK..',
'..KYYYYYYYYYYK..',
'..KYYYYYYYYYYK..',
'...KYYYYYYYYK...',
'...KKKKKKKKKK...',
'................',
'................',
'................',
],
photos: [
'................',
'................',
'....KKKK........',
'...KDDDDK.......',
'.KKKKKKKKKKKKK..',
'.KBBBBBBBBBwBK..',
'.KBBKKKKKBBBBK..',
'.KBKWWWWWKBBBK..',
'.KBKWDDDWKBBBK..',
'.KBKWDDDWKBBBK..',
'.KBKWWWWWKBBBK..',
'.KBBKKKKKBBBBK..',
'.KBBBBBBBBBBBK..',
'.KKKKKKKKKKKKK..',
'................',
'................',
],
unstuck: [
'................',
'.....KKKKK......',
'...KKRRRRRKK....',
'..KRRKKKKKRRK...',
'..KRK.....KRK...',
'.KRK..KKK..KRK..',
'.KRK.KRRRK.KRK..',
'.KRK.KRKRK.KRK..',
'.KRK.KRRK..KRK..',
'.KRK..KK..KRK...',
'..KRK.....KRK...',
'..KRRKKKKKRK....',
'...KKRRRRRK.....',
'.....KKKKK......',
'................',
'................',
],
selfcare: [
'................',
'................',
'..KKKK...KKKK...',
'.KNNNNK.KNNNNK..',
'KNNwwNNKNNNNNNK.',
'KNwwNNNNNNNNNNK.',
'KNNNNNNNNNNNNNK.',
'KNNNNNNNNNNNNNK.',
'.KNNNNNNNNNNNK..',
'..KNNNNNNNNNK...',
'...KNNNNNNNK....',
'....KNNNNNK.....',
'.....KNNNK......',
'......KNK.......',
'.......K........',
'................',
],
mixtape: [
'................',
'.KKKKKKKKKKKKKK.',
'.KOOOOOOOOOOOOK.',
'.KOWWWWWWWWWWOK.',
'.KOWYYYYYYYYWOK.',
'.KOWWWWWWWWWWOK.',
'.KOOOOOOOOOOOOK.',
'.KOKKKKKKKKKKOK.',
'.KOKWKKDDKKWKOK.',
'.KOKWKKDDKKWKOK.',
'.KOKKKKKKKKKKOK.',
'.KOOOOOOOOOOOOK.',
'.KOKOOOOOOOOKOK.',
'.KKKKKKKKKKKKKK.',
'................',
'................',
],
media: [
'................',
'...K.......K....',
'....K.....K.....',
'.....K...K......',
'......KKK.......',
'..KKKKKKKKKKKK..',
'..KRRRRRRRRRRK..',
'..KRKKKKKKKRRK..',
'..KRKLLLLLKRwK..',
'..KRKLLWLLKRRK..',
'..KRKLLLLLKRwK..',
'..KRKKKKKKKRRK..',
'..KRRRRRRRRRRK..',
'..KKKKKKKKKKKK..',
'...KK......KK...',
'................',
],
games: [
'................',
'................',
'................',
'...KKKKKKKKKK...',
'..KPPPPPPPPPPK..',
'.KPPKWKPPPPPPPK.',
'.KPKWWWKPPRPPPK.',
'.KPPKWKPPRPRPPK.',
'.KPPPPPPPPRPPPK.',
'.KPPPPPPPPPPPPK.',
'.KPKPPPPPPPPKPK.',
'..KKPPPKKPPPKK..',
'...KKKK..KKKK...',
'................',
'................',
'................',
],
shortcuts: [
'................',
'........KKKK....',
'.......KYYYK....',
'......KYYYK.....',
'.....KYYYK......',
'....KYYYK.......',
'...KYYYYKKKK....',
'..KYYYYYYYYK....',
'..KKKKYYYYK.....',
'......KYYK......',
'.....KYYK.......',
'....KYYK........',
'....KYK.........',
'...KK...........',
'................',
'................',
],
launcher: [
'................',
'.....KKKKKK.....',
'...KKBBBBBBKK...',
'..KBBBGGBBBBBK..',
'.KBBGGGGGBBBBBK.',
'.KBGGGBBBBBGGBK.',
'.KBBGBBBBBGGGBK.',
'.KBBBBBBBGGGGBK.',
'.KBBBBBBBBGGBBK.',
'.KBGGBBBBBBBBBK.',
'..KBGGGBBBBBBK..',
'...KKBBBBBBKK...',
'.....KKKKKK.....',
'................',
'................',
'................',
],
stats: [
'................',
'..KKKKKKKKKKK...',
'..KYYYYYYYYYK...',
'.KKYYYYYYYYYKK..',
'.KYKYYYYYYYKYK..',
'.KYKYYYYYYYKYK..',
'.KKYYYYYYYYYKK..',
'...KYYYYYYYK....',
'....KYYYYYK.....',
'.....KYYYK......',
'......KYK.......',
'.....KKYKK......',
'....KYYYYYK.....',
'...KKKKKKKKK....',
'................',
'................',
],
sync: [
'................',
'................',
'......KKKK......',
'.....KWWWWK.....',
'...KKWWWWWWKK...',
'..KWWWWWWWWWWK..',
'.KWWWWWWWWWWWWK.',
'.KWWWWWWWWWWWWK.',
'..KKKKKKKKKKKK..',
'....KGK...KBK...',
'...KGGGK..KBK...',
'..KGGGGGK.KBK...',
'....KGK..KBBBK..',
'....KGK...KBK...',
'.....K.....K....',
'................',
],
events: [
'................',
'...KKKKKKKKK....',
'...KOOOOOOOK....',
'....KWWWWWK.....',
'....KWYYYWK.....',
'.....KWYWK......',
'......KYK.......',
'......KYK.......',
'.....KWYWK......',
'....KWWYWWK.....',
'....KWYYYWK.....',
'...KOYYYYYOK....',
'...KKKKKKKKK....',
'................',
'................',
'................',
],
goals: [
'................',
'.....KK.........',
'.....KRRRRK.....',
'.....KRRRRK.....',
'.....KK.........',
'.....KK.........',
'....KWWK........',
'....KWWWK.......',
'...KWWWWWK......',
'...KDWWWDDK.....',
'..KDDWWDDDDK....',
'..KDDDDDDDDK....',
'.KDDDDDDDDDDK...',
'.KKKKKKKKKKKK...',
'................',
'................',
],
money: [
'................',
'.....KKKKK......',
'....KYYYYYK.....',
'.....KKYKK......',
'.....KKKKK......',
'....KGGGGGK.....',
'...KGGGGGGGK....',
'..KGGGKKKGGGK...',
'..KGGKGGGGGGK...',
'..KGGGKKKGGGK...',
'..KGGGGGGKGGK...',
'..KGGGKKKGGGK...',
'...KGGGGGGGK....',
'....KKKKKKK.....',
'................',
'................',
],
people: [
'................',
'....KKKKKKKK....',
'...KYYYYYYYYK...',
'..KYYYYYYYYYYK..',
'.KYYKKYYYYKKYYK.',
'.KYYKKYYYYKKYYK.',
'.KYYYYYYYYYYYYK.',
'.KNNYYYYYYYYNNK.',
'.KNNYKYYYYKYNNK.',
'..KYYKKKKKKYYK..',
'..KYYYYYYYYYK...',
'...KYYYYYYYK....',
'....KKKKKKKK....',
'................',
'................',
'................',
],
weather: [
'................',
'.......KKK......',
'......KYYYK.....',
'.....KYYYYYK....',
'.....KYYYYYK....',
'....KKYYYYKK....',
'...KWWKKKKWWK...',
'..KWWWWWWWWWWK..',
'.KWWWWWWWWWWWWK.',
'.KWWWWWWWWWWWWK.',
'..KKKKKKKKKKKK..',
'....L...L...L...',
'...L...L...L....',
'................',
'................',
'................',
],
doodle: [
'................',
'..........KKK...',
'.........KNNNK..',
'........KNNNNK..',
'.......KNNNNK...',
'......KNNNNK....',
'.....KNNNNK.....',
'....KWWNNK......',
'....KWWWK.......',
'...KWWWK........',
'...KKKK.........',
'..KKK...........',
'.KOOK.KOO.......',
'.KOKOOKOK.......',
'................',
'................',
],
calc: [
'................',
'..KKKKKKKKKKKK..',
'..KPPPPPPPPPPK..',
'..KPWWWWWWWWPK..',
'..KPWWWWWWWWPK..',
'..KPPPPPPPPPPK..',
'..KPWWPWWPWWPK..',
'..KPPPPPPPPPPK..',
'..KPWWPWWPWWPK..',
'..KPPPPPPPPPPK..',
'..KPWWPWWPGGPK..',
'..KPPPPPPPPPPK..',
'..KKKKKKKKKKKK..',
'................',
'................',
'................',
],
oracle: [
'................',
'................',
'.....KKKKKK.....',
'...KKPPPPPPKK...',
'..KPPwwPPPPPPK..',
'..KPwwPPPPPPPK..',
'.KPPwPPPPPPPPPK.',
'.KPPPPPPPPPPPPK.',
'.KPPPPPPPPPPPPK.',
'..KPPPPPPPPPPK..',
'...KKPPPPPPKK...',
'.....KKKKKK.....',
'....KYYYYYYK....',
'...KYYYYYYYYK...',
'...KKKKKKKKKK...',
'................',
],
calendar: [
'................',
'....KK....KK....',
'....KK....KK....',
'..KKKKKKKKKKKK..',
'..KRRRRRRRRRRK..',
'..KRRRRRRRRRRK..',
'..KKKKKKKKKKKK..',
'..KWWWWWWWWWWK..',
'..KWKKWKKWKKWK..',
'..KWWWWWWWWWWK..',
'..KWKKWOOWKKWK..',
'..KWWWWWWWWWWK..',
'..KWKKWKKWKKWK..',
'..KWWWWWWWWWWK..',
'..KKKKKKKKKKKK..',
'................',
],
habits: [
'................',
'.......K........',
'......KOK.......',
'......KOK.......',
'.....KOOK.......',
'.....KOOOK......',
'....KOOOOK......',
'...KOOOOOOK.....',
'..KOOYYYOOK.....',
'..KOYYYYYOOK....',
'..KOYYWYYYOK....',
'..KOYYWWYYOK....',
'..KOOYYYYOOK....',
'...KOOOOOOK.....',
'....KKKKKK......',
'................',
],
clock: [
'................',
'..KKK......KKK..',
'.KYYYK....KYYYK.',
'.KYYYK....KYYYK.',
'..KKKKKKKKKKKK..',
'....KWWWWWWK....',
'...KWWWKWWWWK...',
'..KWWWWKWWWWWK..',
'..KWWWWKKKWWWK..',
'..KWWWWWWWWWWK..',
'..KWWWWWWWWWWK..',
'...KWWWWWWWWK...',
'....KWWWWWWK....',
'.....KKKKKK.....',
'....KK....KK....',
'................',
],
};

/* decorative sprites for the desktop */
const DECOR = {
cloud1: [
'......KKKK......',
'.....KWWWWK.....',
'..KKKWWWWWWKKK..',
'.KWWWWWWWWWWWWK.',
'KWWWWWWWWWWWWWWK',
'.KKKKKKKKKKKKKK.',
],
cloud2: [
'....KKKK....',
'..KKWWWWKK..',
'.KWWWWWWWWK.',
'KWWWWWWWWWWK',
'.KKKKKKKKKK.',
],
sun: [
'....KKKK....',
'..KKYYYYKK..',
'.KYYYOOYYYK.',
'.KYYOOOOYYK.',
'.KYYOOOOYYK.',
'.KYYYOOYYYK.',
'..KKYYYYKK..',
'....KKKK....',
],
waves: [
'..KK......KK......KK......KK....',
'.KBBK....KBBK....KBBK....KBBK...',
'KB..BKKKKB..BKKKKB..BKKKKB..BKKK',
'................................',
'....KK......KK......KK......KK..',
'...KLLK....KLLK....KLLK....KLLK.',
'KKKL..LKKKKL..LKKKKL..LKKKKL..LK',
],
};

function toSVG(map, px = 4) {
  const h = map.length, w = map[0].length;
  let rects = '';
  map.forEach((row, y) => {
    if (row.length !== w) throw new Error('bad row length ' + row.length + ' vs ' + w + ': "' + row + '"');
    // run-length encode rows for smaller files
    let x = 0;
    while (x < w) {
      const c = row[x];
      if (c === '.' || !PAL[c]) { x++; continue; }
      let x2 = x + 1;
      while (x2 < w && row[x2] === c) x2++;
      rects += `<rect x="${x * px}" y="${y * px}" width="${(x2 - x) * px}" height="${px}" fill="${PAL[c]}"/>`;
      x = x2;
    }
  });
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w * px} ${h * px}" shape-rendering="crispEdges">${rects}</svg>`;
}

for (const [name, map] of Object.entries(ICONS)) {
  fs.writeFileSync(`assets/icons/${name}.svg`, toSVG(map));
}
for (const [name, map] of Object.entries(DECOR)) {
  fs.writeFileSync(`assets/decor-${name}.svg`, toSVG(map));
}
console.log(Object.keys(ICONS).length, 'icons +', Object.keys(DECOR).length, 'decor sprites written');
